name: Test Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: macos-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
    strategy:
      matrix:
        include:
          - destination: platform=iOS Simulator,name=iPhone 13

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Install SPM Dependencies
        run: |
          xcodebuild -resolvePackageDependencies -scmProvider system

      - name: Build (${{ matrix.ios }})
        run: |
          xcodebuild -project Foneta.xcodeproj \
            -scheme Foneta \
            -destination '${{matrix.destination}}' \
            build \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO \
            | xcpretty && exit ${PIPESTATUS[0]}

      # - name: Test (${{ matrix.ios }})
      #   run: |
      #     xcodebuild -project Foneta.xcodeproj \
      #       -scheme Foneta \
      #       -destination '${{matrix.destination}}' \
      #       clean test \
      #       CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO \
      #       | xcpretty && exit ${PIPESTATUS[0]}
      